### PR TITLE
Rewrite before going live on bangordailynews.com

### PR DESCRIPTION
**Pull request by wpdavis**
Rewrote the plugin to be object-oriented, reduce duplicate code, more respect script and style order and such.

### CODE REVIEW

**Comment by staylor** [comment]
Can you resolve this with the other PR I just accepted? Even if you have to delete some of the changes

**Comment by staylor** [comment]
Actually, I'll look at it

**Comment by wpdavis** [comment]
Happy to take a look. I have a few other changes for this, too.

**Comment by staylor** [comment]
ok, go ahead - I'll do a scan once you freshen up the PR

**Pull request closed without merging**
